# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d79be5de6776622964db6ed6cddad5b284ebbe826aaff3b9dd96f99c70a9cda3f73995a49b584ab1e573e2d8b7890a2a999bfbad5e3966e4efc5d4a7cb1eb3d

test:
  secret_key_base: 2ce7513d05ccde873cc4cc9c3d13e398eec745bb3344fb468093797deed9e93327d13ec22244c79a3d57912475cecb8cae2294ba4b083969fa93f2ab7bfc6146

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
